# Generated by Django 4.1.7 on 2023-08-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.area', verbose_name='Area Name'),
            preserve_default=False,
        ),
    ]
