# Generated by Django 4.1.2 on 2023-12-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parashootapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFour',
            fields=[
                ('CategoryFourID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Cateory Four Name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOne',
            fields=[
                ('CategoryOneID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='CategoryOne Name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryThree',
            fields=[
                ('CategoryThreeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Category Three Name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTwo',
            fields=[
                ('CategoryTwoID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='CategoryTwo Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255, verbose_name='Product Name')),
                ('ProductCode', models.CharField(max_length=255, verbose_name='Product Code')),
                ('Barcode', models.ImageField(upload_to='media/profile_pic')),
                ('SalesPrice', models.BigIntegerField(verbose_name='Sales Price')),
                ('CostPrice', models.BigIntegerField(verbose_name='Cost Price')),
                ('CommissionRate', models.BigIntegerField(verbose_name='Commission Rate')),
                ('MaxPrice', models.BigIntegerField(verbose_name='Maximum Price')),
                ('MinPrice', models.BigIntegerField(verbose_name='Minimum Price')),
                ('PerBoxPiece', models.BigIntegerField(verbose_name='Per Box Piece')),
                ('MarketingMaxPrice', models.BigIntegerField(verbose_name='MarketingMaxPrice')),
                ('MarketingMinPrice', models.BigIntegerField(verbose_name='MarketingMinPrice')),
                ('PerBoraPiece', models.BigIntegerField(verbose_name='PerBoraPiece')),
                ('AdminMaxPrice', models.BigIntegerField(verbose_name='AdminMaxPrice')),
                ('AdminMinPrice', models.BigIntegerField(verbose_name='AdminMinPrice')),
                ('ProductImage', models.ImageField(upload_to='media/profile_pic')),
                ('Description', models.TextField()),
                ('Gata', models.CharField(max_length=255, verbose_name='Gata')),
                ('TitleMaterial', models.CharField(max_length=255, verbose_name='Title Material')),
                ('Aster', models.CharField(max_length=255, verbose_name='Aster')),
                ('InnerMaterial', models.CharField(max_length=255, verbose_name='Inner Material')),
                ('PagesSheet', models.CharField(max_length=255, verbose_name='Pages and Sheet')),
                ('PrintingRollingColor', models.CharField(max_length=255, verbose_name='Priting Rolling Color')),
                ('CategoryFour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.categoryfour', verbose_name='Category Four')),
                ('CategoryOne', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.categoryone', verbose_name='Category One')),
                ('CategoryThree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.categorythree', verbose_name='Category Three')),
                ('CategoryTwo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.categorytwo', verbose_name='Category Two')),
                ('Classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.classes', verbose_name='Classes')),
                ('Options', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.options', verbose_name='Options')),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.productcategory', verbose_name='Product Category')),
            ],
        ),
    ]
