# Generated by Django 4.1.2 on 2024-01-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parashootapp', '0003_lot_mazdoor_warehouse_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, unique=True, verbose_name='Accounts Name')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('LedgerEntryID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parashootapp.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parashootapp.transaction')),
            ],
        ),
    ]
