# Generated by Django 4.1.2 on 2024-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parashootapp', '0004_account_transaction_ledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Name',
            field=models.CharField(default=1, max_length=255, verbose_name='Transaction Name'),
            preserve_default=False,
        ),
    ]
