# Generated by Django 4.1.2 on 2024-02-27 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parashootapp', '0005_transaction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Employee Name')),
            ],
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='CreditAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='DebitAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('SalaryID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary Amount')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.account')),
                ('Employees', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parashootapp.employees')),
            ],
        ),
    ]
